package voiceservicescommunicationsgateway

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdktf/cdktf-provider-azurerm-go/azurerm/v7/jsii"

	"github.com/aws/constructs-go/constructs/v10"
	"github.com/cdktf/cdktf-provider-azurerm-go/azurerm/v7/voiceservicescommunicationsgateway/internal"
	"github.com/hashicorp/terraform-cdk-go/cdktf"
)

// Represents a {@link https://registry.terraform.io/providers/hashicorp/azurerm/3.60.0/docs/resources/voice_services_communications_gateway azurerm_voice_services_communications_gateway}.
type VoiceServicesCommunicationsGateway interface {
	cdktf.TerraformResource
	ApiBridge() *string
	SetApiBridge(val *string)
	ApiBridgeInput() *string
	AutoGeneratedDomainNameLabelScope() *string
	SetAutoGeneratedDomainNameLabelScope(val *string)
	AutoGeneratedDomainNameLabelScopeInput() *string
	// Experimental.
	CdktfStack() cdktf.TerraformStack
	Codecs() *string
	SetCodecs(val *string)
	CodecsInput() *string
	// Experimental.
	Connection() interface{}
	// Experimental.
	SetConnection(val interface{})
	Connectivity() *string
	SetConnectivity(val *string)
	ConnectivityInput() *string
	// Experimental.
	ConstructNodeMetadata() *map[string]interface{}
	// Experimental.
	Count() interface{}
	// Experimental.
	SetCount(val interface{})
	// Experimental.
	DependsOn() *[]*string
	// Experimental.
	SetDependsOn(val *[]*string)
	E911Type() *string
	SetE911Type(val *string)
	E911TypeInput() *string
	EmergencyDialStrings() *[]*string
	SetEmergencyDialStrings(val *[]*string)
	EmergencyDialStringsInput() *[]*string
	// Experimental.
	ForEach() cdktf.ITerraformIterator
	// Experimental.
	SetForEach(val cdktf.ITerraformIterator)
	// Experimental.
	Fqn() *string
	// Experimental.
	FriendlyUniqueId() *string
	Id() *string
	SetId(val *string)
	IdInput() *string
	// Experimental.
	Lifecycle() *cdktf.TerraformResourceLifecycle
	// Experimental.
	SetLifecycle(val *cdktf.TerraformResourceLifecycle)
	Location() *string
	SetLocation(val *string)
	LocationInput() *string
	MicrosoftTeamsVoicemailPilotNumber() *string
	SetMicrosoftTeamsVoicemailPilotNumber(val *string)
	MicrosoftTeamsVoicemailPilotNumberInput() *string
	Name() *string
	SetName(val *string)
	NameInput() *string
	// The tree node.
	Node() constructs.Node
	OnPremMcpEnabled() interface{}
	SetOnPremMcpEnabled(val interface{})
	OnPremMcpEnabledInput() interface{}
	Platforms() *[]*string
	SetPlatforms(val *[]*string)
	PlatformsInput() *[]*string
	// Experimental.
	Provider() cdktf.TerraformProvider
	// Experimental.
	SetProvider(val cdktf.TerraformProvider)
	// Experimental.
	Provisioners() *[]interface{}
	// Experimental.
	SetProvisioners(val *[]interface{})
	// Experimental.
	RawOverrides() interface{}
	ResourceGroupName() *string
	SetResourceGroupName(val *string)
	ResourceGroupNameInput() *string
	ServiceLocation() VoiceServicesCommunicationsGatewayServiceLocationList
	ServiceLocationInput() interface{}
	Tags() *map[string]*string
	SetTags(val *map[string]*string)
	TagsInput() *map[string]*string
	// Experimental.
	TerraformGeneratorMetadata() *cdktf.TerraformProviderGeneratorMetadata
	// Experimental.
	TerraformMetaArguments() *map[string]interface{}
	// Experimental.
	TerraformResourceType() *string
	Timeouts() VoiceServicesCommunicationsGatewayTimeoutsOutputReference
	TimeoutsInput() interface{}
	// Experimental.
	AddOverride(path *string, value interface{})
	// Experimental.
	GetAnyMapAttribute(terraformAttribute *string) *map[string]interface{}
	// Experimental.
	GetBooleanAttribute(terraformAttribute *string) cdktf.IResolvable
	// Experimental.
	GetBooleanMapAttribute(terraformAttribute *string) *map[string]*bool
	// Experimental.
	GetListAttribute(terraformAttribute *string) *[]*string
	// Experimental.
	GetNumberAttribute(terraformAttribute *string) *float64
	// Experimental.
	GetNumberListAttribute(terraformAttribute *string) *[]*float64
	// Experimental.
	GetNumberMapAttribute(terraformAttribute *string) *map[string]*float64
	// Experimental.
	GetStringAttribute(terraformAttribute *string) *string
	// Experimental.
	GetStringMapAttribute(terraformAttribute *string) *map[string]*string
	// Experimental.
	InterpolationForAttribute(terraformAttribute *string) cdktf.IResolvable
	// Overrides the auto-generated logical ID with a specific ID.
	// Experimental.
	OverrideLogicalId(newLogicalId *string)
	PutServiceLocation(value interface{})
	PutTimeouts(value *VoiceServicesCommunicationsGatewayTimeouts)
	ResetApiBridge()
	ResetAutoGeneratedDomainNameLabelScope()
	ResetEmergencyDialStrings()
	ResetId()
	ResetMicrosoftTeamsVoicemailPilotNumber()
	ResetOnPremMcpEnabled()
	// Resets a previously passed logical Id to use the auto-generated logical id again.
	// Experimental.
	ResetOverrideLogicalId()
	ResetTags()
	ResetTimeouts()
	SynthesizeAttributes() *map[string]interface{}
	// Experimental.
	ToMetadata() interface{}
	// Returns a string representation of this construct.
	ToString() *string
	// Adds this resource to the terraform JSON output.
	// Experimental.
	ToTerraform() interface{}
}

// The jsii proxy struct for VoiceServicesCommunicationsGateway
type jsiiProxy_VoiceServicesCommunicationsGateway struct {
	internal.Type__cdktfTerraformResource
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ApiBridge() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiBridge",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ApiBridgeInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiBridgeInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) AutoGeneratedDomainNameLabelScope() *string {
	var returns *string
	_jsii_.Get(
		j,
		"autoGeneratedDomainNameLabelScope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) AutoGeneratedDomainNameLabelScopeInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"autoGeneratedDomainNameLabelScopeInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) CdktfStack() cdktf.TerraformStack {
	var returns cdktf.TerraformStack
	_jsii_.Get(
		j,
		"cdktfStack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Codecs() *string {
	var returns *string
	_jsii_.Get(
		j,
		"codecs",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) CodecsInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"codecsInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Connection() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"connection",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Connectivity() *string {
	var returns *string
	_jsii_.Get(
		j,
		"connectivity",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ConnectivityInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"connectivityInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ConstructNodeMetadata() *map[string]interface{} {
	var returns *map[string]interface{}
	_jsii_.Get(
		j,
		"constructNodeMetadata",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Count() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"count",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) DependsOn() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"dependsOn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) E911Type() *string {
	var returns *string
	_jsii_.Get(
		j,
		"e911Type",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) E911TypeInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"e911TypeInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) EmergencyDialStrings() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"emergencyDialStrings",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) EmergencyDialStringsInput() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"emergencyDialStringsInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ForEach() cdktf.ITerraformIterator {
	var returns cdktf.ITerraformIterator
	_jsii_.Get(
		j,
		"forEach",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Fqn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"fqn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) FriendlyUniqueId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"friendlyUniqueId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) IdInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"idInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Lifecycle() *cdktf.TerraformResourceLifecycle {
	var returns *cdktf.TerraformResourceLifecycle
	_jsii_.Get(
		j,
		"lifecycle",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Location() *string {
	var returns *string
	_jsii_.Get(
		j,
		"location",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) LocationInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"locationInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) MicrosoftTeamsVoicemailPilotNumber() *string {
	var returns *string
	_jsii_.Get(
		j,
		"microsoftTeamsVoicemailPilotNumber",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) MicrosoftTeamsVoicemailPilotNumberInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"microsoftTeamsVoicemailPilotNumberInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) NameInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"nameInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) OnPremMcpEnabled() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"onPremMcpEnabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) OnPremMcpEnabledInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"onPremMcpEnabledInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Platforms() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"platforms",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) PlatformsInput() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"platformsInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Provider() cdktf.TerraformProvider {
	var returns cdktf.TerraformProvider
	_jsii_.Get(
		j,
		"provider",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Provisioners() *[]interface{} {
	var returns *[]interface{}
	_jsii_.Get(
		j,
		"provisioners",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) RawOverrides() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"rawOverrides",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ResourceGroupName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"resourceGroupName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ResourceGroupNameInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"resourceGroupNameInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ServiceLocation() VoiceServicesCommunicationsGatewayServiceLocationList {
	var returns VoiceServicesCommunicationsGatewayServiceLocationList
	_jsii_.Get(
		j,
		"serviceLocation",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) ServiceLocationInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"serviceLocationInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Tags() *map[string]*string {
	var returns *map[string]*string
	_jsii_.Get(
		j,
		"tags",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) TagsInput() *map[string]*string {
	var returns *map[string]*string
	_jsii_.Get(
		j,
		"tagsInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) TerraformGeneratorMetadata() *cdktf.TerraformProviderGeneratorMetadata {
	var returns *cdktf.TerraformProviderGeneratorMetadata
	_jsii_.Get(
		j,
		"terraformGeneratorMetadata",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) TerraformMetaArguments() *map[string]interface{} {
	var returns *map[string]interface{}
	_jsii_.Get(
		j,
		"terraformMetaArguments",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) TerraformResourceType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"terraformResourceType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) Timeouts() VoiceServicesCommunicationsGatewayTimeoutsOutputReference {
	var returns VoiceServicesCommunicationsGatewayTimeoutsOutputReference
	_jsii_.Get(
		j,
		"timeouts",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) TimeoutsInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"timeoutsInput",
		&returns,
	)
	return returns
}


// Create a new {@link https://registry.terraform.io/providers/hashicorp/azurerm/3.60.0/docs/resources/voice_services_communications_gateway azurerm_voice_services_communications_gateway} Resource.
func NewVoiceServicesCommunicationsGateway(scope constructs.Construct, id *string, config *VoiceServicesCommunicationsGatewayConfig) VoiceServicesCommunicationsGateway {
	_init_.Initialize()

	if err := validateNewVoiceServicesCommunicationsGatewayParameters(scope, id, config); err != nil {
		panic(err)
	}
	j := jsiiProxy_VoiceServicesCommunicationsGateway{}

	_jsii_.Create(
		"@cdktf/provider-azurerm.voiceServicesCommunicationsGateway.VoiceServicesCommunicationsGateway",
		[]interface{}{scope, id, config},
		&j,
	)

	return &j
}

// Create a new {@link https://registry.terraform.io/providers/hashicorp/azurerm/3.60.0/docs/resources/voice_services_communications_gateway azurerm_voice_services_communications_gateway} Resource.
func NewVoiceServicesCommunicationsGateway_Override(v VoiceServicesCommunicationsGateway, scope constructs.Construct, id *string, config *VoiceServicesCommunicationsGatewayConfig) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdktf/provider-azurerm.voiceServicesCommunicationsGateway.VoiceServicesCommunicationsGateway",
		[]interface{}{scope, id, config},
		v,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetApiBridge(val *string) {
	if err := j.validateSetApiBridgeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"apiBridge",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetAutoGeneratedDomainNameLabelScope(val *string) {
	if err := j.validateSetAutoGeneratedDomainNameLabelScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"autoGeneratedDomainNameLabelScope",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetCodecs(val *string) {
	if err := j.validateSetCodecsParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"codecs",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetConnection(val interface{}) {
	if err := j.validateSetConnectionParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"connection",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetConnectivity(val *string) {
	if err := j.validateSetConnectivityParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"connectivity",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetCount(val interface{}) {
	if err := j.validateSetCountParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"count",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetDependsOn(val *[]*string) {
	_jsii_.Set(
		j,
		"dependsOn",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetE911Type(val *string) {
	if err := j.validateSetE911TypeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"e911Type",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetEmergencyDialStrings(val *[]*string) {
	if err := j.validateSetEmergencyDialStringsParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"emergencyDialStrings",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetForEach(val cdktf.ITerraformIterator) {
	_jsii_.Set(
		j,
		"forEach",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetLifecycle(val *cdktf.TerraformResourceLifecycle) {
	if err := j.validateSetLifecycleParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"lifecycle",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetLocation(val *string) {
	if err := j.validateSetLocationParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"location",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetMicrosoftTeamsVoicemailPilotNumber(val *string) {
	if err := j.validateSetMicrosoftTeamsVoicemailPilotNumberParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"microsoftTeamsVoicemailPilotNumber",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetName(val *string) {
	if err := j.validateSetNameParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"name",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetOnPremMcpEnabled(val interface{}) {
	if err := j.validateSetOnPremMcpEnabledParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"onPremMcpEnabled",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetPlatforms(val *[]*string) {
	if err := j.validateSetPlatformsParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"platforms",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetProvider(val cdktf.TerraformProvider) {
	_jsii_.Set(
		j,
		"provider",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetProvisioners(val *[]interface{}) {
	if err := j.validateSetProvisionersParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"provisioners",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetResourceGroupName(val *string) {
	if err := j.validateSetResourceGroupNameParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"resourceGroupName",
		val,
	)
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway)SetTags(val *map[string]*string) {
	if err := j.validateSetTagsParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"tags",
		val,
	)
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
func VoiceServicesCommunicationsGateway_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateVoiceServicesCommunicationsGateway_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdktf/provider-azurerm.voiceServicesCommunicationsGateway.VoiceServicesCommunicationsGateway",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Experimental.
func VoiceServicesCommunicationsGateway_IsTerraformElement(x interface{}) *bool {
	_init_.Initialize()

	if err := validateVoiceServicesCommunicationsGateway_IsTerraformElementParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdktf/provider-azurerm.voiceServicesCommunicationsGateway.VoiceServicesCommunicationsGateway",
		"isTerraformElement",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Experimental.
func VoiceServicesCommunicationsGateway_IsTerraformResource(x interface{}) *bool {
	_init_.Initialize()

	if err := validateVoiceServicesCommunicationsGateway_IsTerraformResourceParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdktf/provider-azurerm.voiceServicesCommunicationsGateway.VoiceServicesCommunicationsGateway",
		"isTerraformResource",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func VoiceServicesCommunicationsGateway_TfResourceType() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"@cdktf/provider-azurerm.voiceServicesCommunicationsGateway.VoiceServicesCommunicationsGateway",
		"tfResourceType",
		&returns,
	)
	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) AddOverride(path *string, value interface{}) {
	if err := v.validateAddOverrideParameters(path, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		v,
		"addOverride",
		[]interface{}{path, value},
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetAnyMapAttribute(terraformAttribute *string) *map[string]interface{} {
	if err := v.validateGetAnyMapAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *map[string]interface{}

	_jsii_.Invoke(
		v,
		"getAnyMapAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetBooleanAttribute(terraformAttribute *string) cdktf.IResolvable {
	if err := v.validateGetBooleanAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns cdktf.IResolvable

	_jsii_.Invoke(
		v,
		"getBooleanAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetBooleanMapAttribute(terraformAttribute *string) *map[string]*bool {
	if err := v.validateGetBooleanMapAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *map[string]*bool

	_jsii_.Invoke(
		v,
		"getBooleanMapAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetListAttribute(terraformAttribute *string) *[]*string {
	if err := v.validateGetListAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *[]*string

	_jsii_.Invoke(
		v,
		"getListAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetNumberAttribute(terraformAttribute *string) *float64 {
	if err := v.validateGetNumberAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *float64

	_jsii_.Invoke(
		v,
		"getNumberAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetNumberListAttribute(terraformAttribute *string) *[]*float64 {
	if err := v.validateGetNumberListAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *[]*float64

	_jsii_.Invoke(
		v,
		"getNumberListAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetNumberMapAttribute(terraformAttribute *string) *map[string]*float64 {
	if err := v.validateGetNumberMapAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *map[string]*float64

	_jsii_.Invoke(
		v,
		"getNumberMapAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetStringAttribute(terraformAttribute *string) *string {
	if err := v.validateGetStringAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getStringAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) GetStringMapAttribute(terraformAttribute *string) *map[string]*string {
	if err := v.validateGetStringMapAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *map[string]*string

	_jsii_.Invoke(
		v,
		"getStringMapAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) InterpolationForAttribute(terraformAttribute *string) cdktf.IResolvable {
	if err := v.validateInterpolationForAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns cdktf.IResolvable

	_jsii_.Invoke(
		v,
		"interpolationForAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) OverrideLogicalId(newLogicalId *string) {
	if err := v.validateOverrideLogicalIdParameters(newLogicalId); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		v,
		"overrideLogicalId",
		[]interface{}{newLogicalId},
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) PutServiceLocation(value interface{}) {
	if err := v.validatePutServiceLocationParameters(value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		v,
		"putServiceLocation",
		[]interface{}{value},
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) PutTimeouts(value *VoiceServicesCommunicationsGatewayTimeouts) {
	if err := v.validatePutTimeoutsParameters(value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		v,
		"putTimeouts",
		[]interface{}{value},
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetApiBridge() {
	_jsii_.InvokeVoid(
		v,
		"resetApiBridge",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetAutoGeneratedDomainNameLabelScope() {
	_jsii_.InvokeVoid(
		v,
		"resetAutoGeneratedDomainNameLabelScope",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetEmergencyDialStrings() {
	_jsii_.InvokeVoid(
		v,
		"resetEmergencyDialStrings",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetId() {
	_jsii_.InvokeVoid(
		v,
		"resetId",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetMicrosoftTeamsVoicemailPilotNumber() {
	_jsii_.InvokeVoid(
		v,
		"resetMicrosoftTeamsVoicemailPilotNumber",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetOnPremMcpEnabled() {
	_jsii_.InvokeVoid(
		v,
		"resetOnPremMcpEnabled",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetOverrideLogicalId() {
	_jsii_.InvokeVoid(
		v,
		"resetOverrideLogicalId",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetTags() {
	_jsii_.InvokeVoid(
		v,
		"resetTags",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ResetTimeouts() {
	_jsii_.InvokeVoid(
		v,
		"resetTimeouts",
		nil, // no parameters
	)
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) SynthesizeAttributes() *map[string]interface{} {
	var returns *map[string]interface{}

	_jsii_.Invoke(
		v,
		"synthesizeAttributes",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ToMetadata() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		v,
		"toMetadata",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) ToTerraform() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		v,
		"toTerraform",
		nil, // no parameters
		&returns,
	)

	return returns
}

