//go:build no_runtime_type_checking

package voiceservicescommunicationsgateway

// Building without runtime type checking enabled, so all the below just return nil

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateAddOverrideParameters(path *string, value interface{}) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validateOverrideLogicalIdParameters(newLogicalId *string) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validatePutServiceLocationParameters(value interface{}) error {
	return nil
}

func (v *jsiiProxy_VoiceServicesCommunicationsGateway) validatePutTimeoutsParameters(value *VoiceServicesCommunicationsGatewayTimeouts) error {
	return nil
}

func validateVoiceServicesCommunicationsGateway_IsConstructParameters(x interface{}) error {
	return nil
}

func validateVoiceServicesCommunicationsGateway_IsTerraformElementParameters(x interface{}) error {
	return nil
}

func validateVoiceServicesCommunicationsGateway_IsTerraformResourceParameters(x interface{}) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetApiBridgeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetAutoGeneratedDomainNameLabelScopeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetCodecsParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetConnectionParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetConnectivityParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetE911TypeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetEmergencyDialStringsParameters(val *[]*string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetIdParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetLifecycleParameters(val *cdktf.TerraformResourceLifecycle) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetLocationParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetMicrosoftTeamsVoicemailPilotNumberParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetNameParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetOnPremMcpEnabledParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetPlatformsParameters(val *[]*string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetProvisionersParameters(val *[]interface{}) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetResourceGroupNameParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_VoiceServicesCommunicationsGateway) validateSetTagsParameters(val *map[string]*string) error {
	return nil
}

func validateNewVoiceServicesCommunicationsGatewayParameters(scope constructs.Construct, id *string, config *VoiceServicesCommunicationsGatewayConfig) error {
	return nil
}

