// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package mobilenetworkattacheddatanetwork

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-azurerm.mobileNetworkAttachedDataNetwork.MobileNetworkAttachedDataNetwork",
		reflect.TypeOf((*MobileNetworkAttachedDataNetwork)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "dnsAddresses", GoGetter: "DnsAddresses"},
			_jsii_.MemberProperty{JsiiProperty: "dnsAddressesInput", GoGetter: "DnsAddressesInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "location", GoGetter: "Location"},
			_jsii_.MemberProperty{JsiiProperty: "locationInput", GoGetter: "LocationInput"},
			_jsii_.MemberProperty{JsiiProperty: "mobileNetworkDataNetworkName", GoGetter: "MobileNetworkDataNetworkName"},
			_jsii_.MemberProperty{JsiiProperty: "mobileNetworkDataNetworkNameInput", GoGetter: "MobileNetworkDataNetworkNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "mobileNetworkPacketCoreDataPlaneId", GoGetter: "MobileNetworkPacketCoreDataPlaneId"},
			_jsii_.MemberProperty{JsiiProperty: "mobileNetworkPacketCoreDataPlaneIdInput", GoGetter: "MobileNetworkPacketCoreDataPlaneIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberProperty{JsiiProperty: "networkAddressPortTranslation", GoGetter: "NetworkAddressPortTranslation"},
			_jsii_.MemberProperty{JsiiProperty: "networkAddressPortTranslationInput", GoGetter: "NetworkAddressPortTranslationInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putNetworkAddressPortTranslation", GoMethod: "PutNetworkAddressPortTranslation"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkAddressPortTranslation", GoMethod: "ResetNetworkAddressPortTranslation"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserEquipmentAddressPoolPrefixes", GoMethod: "ResetUserEquipmentAddressPoolPrefixes"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserEquipmentStaticAddressPoolPrefixes", GoMethod: "ResetUserEquipmentStaticAddressPoolPrefixes"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserPlaneAccessIpv4Address", GoMethod: "ResetUserPlaneAccessIpv4Address"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserPlaneAccessIpv4Gateway", GoMethod: "ResetUserPlaneAccessIpv4Gateway"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserPlaneAccessIpv4Subnet", GoMethod: "ResetUserPlaneAccessIpv4Subnet"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserPlaneAccessName", GoMethod: "ResetUserPlaneAccessName"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "userEquipmentAddressPoolPrefixes", GoGetter: "UserEquipmentAddressPoolPrefixes"},
			_jsii_.MemberProperty{JsiiProperty: "userEquipmentAddressPoolPrefixesInput", GoGetter: "UserEquipmentAddressPoolPrefixesInput"},
			_jsii_.MemberProperty{JsiiProperty: "userEquipmentStaticAddressPoolPrefixes", GoGetter: "UserEquipmentStaticAddressPoolPrefixes"},
			_jsii_.MemberProperty{JsiiProperty: "userEquipmentStaticAddressPoolPrefixesInput", GoGetter: "UserEquipmentStaticAddressPoolPrefixesInput"},
			_jsii_.MemberProperty{JsiiProperty: "userPlaneAccessIpv4Address", GoGetter: "UserPlaneAccessIpv4Address"},
			_jsii_.MemberProperty{JsiiProperty: "userPlaneAccessIpv4AddressInput", GoGetter: "UserPlaneAccessIpv4AddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "userPlaneAccessIpv4Gateway", GoGetter: "UserPlaneAccessIpv4Gateway"},
			_jsii_.MemberProperty{JsiiProperty: "userPlaneAccessIpv4GatewayInput", GoGetter: "UserPlaneAccessIpv4GatewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "userPlaneAccessIpv4Subnet", GoGetter: "UserPlaneAccessIpv4Subnet"},
			_jsii_.MemberProperty{JsiiProperty: "userPlaneAccessIpv4SubnetInput", GoGetter: "UserPlaneAccessIpv4SubnetInput"},
			_jsii_.MemberProperty{JsiiProperty: "userPlaneAccessName", GoGetter: "UserPlaneAccessName"},
			_jsii_.MemberProperty{JsiiProperty: "userPlaneAccessNameInput", GoGetter: "UserPlaneAccessNameInput"},
		},
		func() interface{} {
			j := jsiiProxy_MobileNetworkAttachedDataNetwork{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-azurerm.mobileNetworkAttachedDataNetwork.MobileNetworkAttachedDataNetworkConfig",
		reflect.TypeOf((*MobileNetworkAttachedDataNetworkConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-azurerm.mobileNetworkAttachedDataNetwork.MobileNetworkAttachedDataNetworkNetworkAddressPortTranslation",
		reflect.TypeOf((*MobileNetworkAttachedDataNetworkNetworkAddressPortTranslation)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-azurerm.mobileNetworkAttachedDataNetwork.MobileNetworkAttachedDataNetworkNetworkAddressPortTranslationOutputReference",
		reflect.TypeOf((*MobileNetworkAttachedDataNetworkNetworkAddressPortTranslationOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "icmpPinholeTimeoutInSeconds", GoGetter: "IcmpPinholeTimeoutInSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "icmpPinholeTimeoutInSecondsInput", GoGetter: "IcmpPinholeTimeoutInSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "pinholeMaximumNumber", GoGetter: "PinholeMaximumNumber"},
			_jsii_.MemberProperty{JsiiProperty: "pinholeMaximumNumberInput", GoGetter: "PinholeMaximumNumberInput"},
			_jsii_.MemberProperty{JsiiProperty: "portRange", GoGetter: "PortRange"},
			_jsii_.MemberProperty{JsiiProperty: "portRangeInput", GoGetter: "PortRangeInput"},
			_jsii_.MemberMethod{JsiiMethod: "putPortRange", GoMethod: "PutPortRange"},
			_jsii_.MemberMethod{JsiiMethod: "resetIcmpPinholeTimeoutInSeconds", GoMethod: "ResetIcmpPinholeTimeoutInSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetPinholeMaximumNumber", GoMethod: "ResetPinholeMaximumNumber"},
			_jsii_.MemberMethod{JsiiMethod: "resetPortRange", GoMethod: "ResetPortRange"},
			_jsii_.MemberMethod{JsiiMethod: "resetTcpPinholeTimeoutInSeconds", GoMethod: "ResetTcpPinholeTimeoutInSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetTcpPortReuseMinimumHoldTimeInSeconds", GoMethod: "ResetTcpPortReuseMinimumHoldTimeInSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetUdpPinholeTimeoutInSeconds", GoMethod: "ResetUdpPinholeTimeoutInSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetUdpPortReuseMinimumHoldTimeInSeconds", GoMethod: "ResetUdpPortReuseMinimumHoldTimeInSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "tcpPinholeTimeoutInSeconds", GoGetter: "TcpPinholeTimeoutInSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "tcpPinholeTimeoutInSecondsInput", GoGetter: "TcpPinholeTimeoutInSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "tcpPortReuseMinimumHoldTimeInSeconds", GoGetter: "TcpPortReuseMinimumHoldTimeInSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "tcpPortReuseMinimumHoldTimeInSecondsInput", GoGetter: "TcpPortReuseMinimumHoldTimeInSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "udpPinholeTimeoutInSeconds", GoGetter: "UdpPinholeTimeoutInSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "udpPinholeTimeoutInSecondsInput", GoGetter: "UdpPinholeTimeoutInSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "udpPortReuseMinimumHoldTimeInSeconds", GoGetter: "UdpPortReuseMinimumHoldTimeInSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "udpPortReuseMinimumHoldTimeInSecondsInput", GoGetter: "UdpPortReuseMinimumHoldTimeInSecondsInput"},
		},
		func() interface{} {
			j := jsiiProxy_MobileNetworkAttachedDataNetworkNetworkAddressPortTranslationOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-azurerm.mobileNetworkAttachedDataNetwork.MobileNetworkAttachedDataNetworkNetworkAddressPortTranslationPortRange",
		reflect.TypeOf((*MobileNetworkAttachedDataNetworkNetworkAddressPortTranslationPortRange)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-azurerm.mobileNetworkAttachedDataNetwork.MobileNetworkAttachedDataNetworkNetworkAddressPortTranslationPortRangeOutputReference",
		reflect.TypeOf((*MobileNetworkAttachedDataNetworkNetworkAddressPortTranslationPortRangeOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maximum", GoGetter: "Maximum"},
			_jsii_.MemberProperty{JsiiProperty: "maximumInput", GoGetter: "MaximumInput"},
			_jsii_.MemberProperty{JsiiProperty: "minimum", GoGetter: "Minimum"},
			_jsii_.MemberProperty{JsiiProperty: "minimumInput", GoGetter: "MinimumInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaximum", GoMethod: "ResetMaximum"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinimum", GoMethod: "ResetMinimum"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_MobileNetworkAttachedDataNetworkNetworkAddressPortTranslationPortRangeOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-azurerm.mobileNetworkAttachedDataNetwork.MobileNetworkAttachedDataNetworkTimeouts",
		reflect.TypeOf((*MobileNetworkAttachedDataNetworkTimeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-azurerm.mobileNetworkAttachedDataNetwork.MobileNetworkAttachedDataNetworkTimeoutsOutputReference",
		reflect.TypeOf((*MobileNetworkAttachedDataNetworkTimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "read", GoGetter: "Read"},
			_jsii_.MemberProperty{JsiiProperty: "readInput", GoGetter: "ReadInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resetRead", GoMethod: "ResetRead"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdate", GoMethod: "ResetUpdate"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "update", GoGetter: "Update"},
			_jsii_.MemberProperty{JsiiProperty: "updateInput", GoGetter: "UpdateInput"},
		},
		func() interface{} {
			j := jsiiProxy_MobileNetworkAttachedDataNetworkTimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
