// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package cosmosdbpostgresqlcluster

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-azurerm.cosmosdbPostgresqlCluster.CosmosdbPostgresqlCluster",
		reflect.TypeOf((*CosmosdbPostgresqlCluster)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "administratorLoginPassword", GoGetter: "AdministratorLoginPassword"},
			_jsii_.MemberProperty{JsiiProperty: "administratorLoginPasswordInput", GoGetter: "AdministratorLoginPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "citusVersion", GoGetter: "CitusVersion"},
			_jsii_.MemberProperty{JsiiProperty: "citusVersionInput", GoGetter: "CitusVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "coordinatorPublicIpAccessEnabled", GoGetter: "CoordinatorPublicIpAccessEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "coordinatorPublicIpAccessEnabledInput", GoGetter: "CoordinatorPublicIpAccessEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "coordinatorServerEdition", GoGetter: "CoordinatorServerEdition"},
			_jsii_.MemberProperty{JsiiProperty: "coordinatorServerEditionInput", GoGetter: "CoordinatorServerEditionInput"},
			_jsii_.MemberProperty{JsiiProperty: "coordinatorStorageQuotaInMb", GoGetter: "CoordinatorStorageQuotaInMb"},
			_jsii_.MemberProperty{JsiiProperty: "coordinatorStorageQuotaInMbInput", GoGetter: "CoordinatorStorageQuotaInMbInput"},
			_jsii_.MemberProperty{JsiiProperty: "coordinatorVcoreCount", GoGetter: "CoordinatorVcoreCount"},
			_jsii_.MemberProperty{JsiiProperty: "coordinatorVcoreCountInput", GoGetter: "CoordinatorVcoreCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "earliestRestoreTime", GoGetter: "EarliestRestoreTime"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "haEnabled", GoGetter: "HaEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "haEnabledInput", GoGetter: "HaEnabledInput"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "location", GoGetter: "Location"},
			_jsii_.MemberProperty{JsiiProperty: "locationInput", GoGetter: "LocationInput"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindow", GoGetter: "MaintenanceWindow"},
			_jsii_.MemberProperty{JsiiProperty: "maintenanceWindowInput", GoGetter: "MaintenanceWindowInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "nodeCount", GoGetter: "NodeCount"},
			_jsii_.MemberProperty{JsiiProperty: "nodeCountInput", GoGetter: "NodeCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "nodePublicIpAccessEnabled", GoGetter: "NodePublicIpAccessEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "nodePublicIpAccessEnabledInput", GoGetter: "NodePublicIpAccessEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "nodeServerEdition", GoGetter: "NodeServerEdition"},
			_jsii_.MemberProperty{JsiiProperty: "nodeServerEditionInput", GoGetter: "NodeServerEditionInput"},
			_jsii_.MemberProperty{JsiiProperty: "nodeStorageQuotaInMb", GoGetter: "NodeStorageQuotaInMb"},
			_jsii_.MemberProperty{JsiiProperty: "nodeStorageQuotaInMbInput", GoGetter: "NodeStorageQuotaInMbInput"},
			_jsii_.MemberProperty{JsiiProperty: "nodeVcores", GoGetter: "NodeVcores"},
			_jsii_.MemberProperty{JsiiProperty: "nodeVcoresInput", GoGetter: "NodeVcoresInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "pointInTimeInUtc", GoGetter: "PointInTimeInUtc"},
			_jsii_.MemberProperty{JsiiProperty: "pointInTimeInUtcInput", GoGetter: "PointInTimeInUtcInput"},
			_jsii_.MemberProperty{JsiiProperty: "preferredPrimaryZone", GoGetter: "PreferredPrimaryZone"},
			_jsii_.MemberProperty{JsiiProperty: "preferredPrimaryZoneInput", GoGetter: "PreferredPrimaryZoneInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putMaintenanceWindow", GoMethod: "PutMaintenanceWindow"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAdministratorLoginPassword", GoMethod: "ResetAdministratorLoginPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetCitusVersion", GoMethod: "ResetCitusVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetCoordinatorPublicIpAccessEnabled", GoMethod: "ResetCoordinatorPublicIpAccessEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetCoordinatorServerEdition", GoMethod: "ResetCoordinatorServerEdition"},
			_jsii_.MemberMethod{JsiiMethod: "resetCoordinatorStorageQuotaInMb", GoMethod: "ResetCoordinatorStorageQuotaInMb"},
			_jsii_.MemberMethod{JsiiMethod: "resetCoordinatorVcoreCount", GoMethod: "ResetCoordinatorVcoreCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaEnabled", GoMethod: "ResetHaEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaintenanceWindow", GoMethod: "ResetMaintenanceWindow"},
			_jsii_.MemberMethod{JsiiMethod: "resetNodePublicIpAccessEnabled", GoMethod: "ResetNodePublicIpAccessEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetNodeServerEdition", GoMethod: "ResetNodeServerEdition"},
			_jsii_.MemberMethod{JsiiMethod: "resetNodeStorageQuotaInMb", GoMethod: "ResetNodeStorageQuotaInMb"},
			_jsii_.MemberMethod{JsiiMethod: "resetNodeVcores", GoMethod: "ResetNodeVcores"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPointInTimeInUtc", GoMethod: "ResetPointInTimeInUtc"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreferredPrimaryZone", GoMethod: "ResetPreferredPrimaryZone"},
			_jsii_.MemberMethod{JsiiMethod: "resetShardsOnCoordinatorEnabled", GoMethod: "ResetShardsOnCoordinatorEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetSourceLocation", GoMethod: "ResetSourceLocation"},
			_jsii_.MemberMethod{JsiiMethod: "resetSourceResourceId", GoMethod: "ResetSourceResourceId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSqlVersion", GoMethod: "ResetSqlVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "resourceGroupName", GoGetter: "ResourceGroupName"},
			_jsii_.MemberProperty{JsiiProperty: "resourceGroupNameInput", GoGetter: "ResourceGroupNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "shardsOnCoordinatorEnabled", GoGetter: "ShardsOnCoordinatorEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "shardsOnCoordinatorEnabledInput", GoGetter: "ShardsOnCoordinatorEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "sourceLocation", GoGetter: "SourceLocation"},
			_jsii_.MemberProperty{JsiiProperty: "sourceLocationInput", GoGetter: "SourceLocationInput"},
			_jsii_.MemberProperty{JsiiProperty: "sourceResourceId", GoGetter: "SourceResourceId"},
			_jsii_.MemberProperty{JsiiProperty: "sourceResourceIdInput", GoGetter: "SourceResourceIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sqlVersion", GoGetter: "SqlVersion"},
			_jsii_.MemberProperty{JsiiProperty: "sqlVersionInput", GoGetter: "SqlVersionInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_CosmosdbPostgresqlCluster{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-azurerm.cosmosdbPostgresqlCluster.CosmosdbPostgresqlClusterConfig",
		reflect.TypeOf((*CosmosdbPostgresqlClusterConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-azurerm.cosmosdbPostgresqlCluster.CosmosdbPostgresqlClusterMaintenanceWindow",
		reflect.TypeOf((*CosmosdbPostgresqlClusterMaintenanceWindow)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-azurerm.cosmosdbPostgresqlCluster.CosmosdbPostgresqlClusterMaintenanceWindowOutputReference",
		reflect.TypeOf((*CosmosdbPostgresqlClusterMaintenanceWindowOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dayOfWeek", GoGetter: "DayOfWeek"},
			_jsii_.MemberProperty{JsiiProperty: "dayOfWeekInput", GoGetter: "DayOfWeekInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetDayOfWeek", GoMethod: "ResetDayOfWeek"},
			_jsii_.MemberMethod{JsiiMethod: "resetStartHour", GoMethod: "ResetStartHour"},
			_jsii_.MemberMethod{JsiiMethod: "resetStartMinute", GoMethod: "ResetStartMinute"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "startHour", GoGetter: "StartHour"},
			_jsii_.MemberProperty{JsiiProperty: "startHourInput", GoGetter: "StartHourInput"},
			_jsii_.MemberProperty{JsiiProperty: "startMinute", GoGetter: "StartMinute"},
			_jsii_.MemberProperty{JsiiProperty: "startMinuteInput", GoGetter: "StartMinuteInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_CosmosdbPostgresqlClusterMaintenanceWindowOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-azurerm.cosmosdbPostgresqlCluster.CosmosdbPostgresqlClusterTimeouts",
		reflect.TypeOf((*CosmosdbPostgresqlClusterTimeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-azurerm.cosmosdbPostgresqlCluster.CosmosdbPostgresqlClusterTimeoutsOutputReference",
		reflect.TypeOf((*CosmosdbPostgresqlClusterTimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "read", GoGetter: "Read"},
			_jsii_.MemberProperty{JsiiProperty: "readInput", GoGetter: "ReadInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resetRead", GoMethod: "ResetRead"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdate", GoMethod: "ResetUpdate"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "update", GoGetter: "Update"},
			_jsii_.MemberProperty{JsiiProperty: "updateInput", GoGetter: "UpdateInput"},
		},
		func() interface{} {
			j := jsiiProxy_CosmosdbPostgresqlClusterTimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
