// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package dashboardgrafana

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/cdktf/cdktf-provider-azurerm-go/azurerm/v13/jsii"

	"github.com/aws/constructs-go/constructs/v10"
	"github.com/cdktf/cdktf-provider-azurerm-go/azurerm/v13/dashboardgrafana/internal"
	"github.com/hashicorp/terraform-cdk-go/cdktf"
)

// Represents a {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.28.0/docs/resources/dashboard_grafana azurerm_dashboard_grafana}.
type DashboardGrafana interface {
	cdktf.TerraformResource
	ApiKeyEnabled() interface{}
	SetApiKeyEnabled(val interface{})
	ApiKeyEnabledInput() interface{}
	AutoGeneratedDomainNameLabelScope() *string
	SetAutoGeneratedDomainNameLabelScope(val *string)
	AutoGeneratedDomainNameLabelScopeInput() *string
	AzureMonitorWorkspaceIntegrations() DashboardGrafanaAzureMonitorWorkspaceIntegrationsList
	AzureMonitorWorkspaceIntegrationsInput() interface{}
	// Experimental.
	CdktfStack() cdktf.TerraformStack
	// Experimental.
	Connection() interface{}
	// Experimental.
	SetConnection(val interface{})
	// Experimental.
	ConstructNodeMetadata() *map[string]interface{}
	// Experimental.
	Count() interface{}
	// Experimental.
	SetCount(val interface{})
	// Experimental.
	DependsOn() *[]*string
	// Experimental.
	SetDependsOn(val *[]*string)
	DeterministicOutboundIpEnabled() interface{}
	SetDeterministicOutboundIpEnabled(val interface{})
	DeterministicOutboundIpEnabledInput() interface{}
	Endpoint() *string
	// Experimental.
	ForEach() cdktf.ITerraformIterator
	// Experimental.
	SetForEach(val cdktf.ITerraformIterator)
	// Experimental.
	Fqn() *string
	// Experimental.
	FriendlyUniqueId() *string
	GrafanaMajorVersion() *string
	SetGrafanaMajorVersion(val *string)
	GrafanaMajorVersionInput() *string
	GrafanaVersion() *string
	Id() *string
	SetId(val *string)
	Identity() DashboardGrafanaIdentityOutputReference
	IdentityInput() *DashboardGrafanaIdentity
	IdInput() *string
	// Experimental.
	Lifecycle() *cdktf.TerraformResourceLifecycle
	// Experimental.
	SetLifecycle(val *cdktf.TerraformResourceLifecycle)
	Location() *string
	SetLocation(val *string)
	LocationInput() *string
	Name() *string
	SetName(val *string)
	NameInput() *string
	// The tree node.
	Node() constructs.Node
	OutboundIp() *[]*string
	// Experimental.
	Provider() cdktf.TerraformProvider
	// Experimental.
	SetProvider(val cdktf.TerraformProvider)
	// Experimental.
	Provisioners() *[]interface{}
	// Experimental.
	SetProvisioners(val *[]interface{})
	PublicNetworkAccessEnabled() interface{}
	SetPublicNetworkAccessEnabled(val interface{})
	PublicNetworkAccessEnabledInput() interface{}
	// Experimental.
	RawOverrides() interface{}
	ResourceGroupName() *string
	SetResourceGroupName(val *string)
	ResourceGroupNameInput() *string
	Sku() *string
	SetSku(val *string)
	SkuInput() *string
	Smtp() DashboardGrafanaSmtpOutputReference
	SmtpInput() *DashboardGrafanaSmtp
	Tags() *map[string]*string
	SetTags(val *map[string]*string)
	TagsInput() *map[string]*string
	// Experimental.
	TerraformGeneratorMetadata() *cdktf.TerraformProviderGeneratorMetadata
	// Experimental.
	TerraformMetaArguments() *map[string]interface{}
	// Experimental.
	TerraformResourceType() *string
	Timeouts() DashboardGrafanaTimeoutsOutputReference
	TimeoutsInput() interface{}
	ZoneRedundancyEnabled() interface{}
	SetZoneRedundancyEnabled(val interface{})
	ZoneRedundancyEnabledInput() interface{}
	// Adds a user defined moveTarget string to this resource to be later used in .moveTo(moveTarget) to resolve the location of the move.
	// Experimental.
	AddMoveTarget(moveTarget *string)
	// Experimental.
	AddOverride(path *string, value interface{})
	// Experimental.
	GetAnyMapAttribute(terraformAttribute *string) *map[string]interface{}
	// Experimental.
	GetBooleanAttribute(terraformAttribute *string) cdktf.IResolvable
	// Experimental.
	GetBooleanMapAttribute(terraformAttribute *string) *map[string]*bool
	// Experimental.
	GetListAttribute(terraformAttribute *string) *[]*string
	// Experimental.
	GetNumberAttribute(terraformAttribute *string) *float64
	// Experimental.
	GetNumberListAttribute(terraformAttribute *string) *[]*float64
	// Experimental.
	GetNumberMapAttribute(terraformAttribute *string) *map[string]*float64
	// Experimental.
	GetStringAttribute(terraformAttribute *string) *string
	// Experimental.
	GetStringMapAttribute(terraformAttribute *string) *map[string]*string
	// Experimental.
	HasResourceMove() interface{}
	// Experimental.
	ImportFrom(id *string, provider cdktf.TerraformProvider)
	// Experimental.
	InterpolationForAttribute(terraformAttribute *string) cdktf.IResolvable
	// Move the resource corresponding to "id" to this resource.
	//
	// Note that the resource being moved from must be marked as moved using it's instance function.
	// Experimental.
	MoveFromId(id *string)
	// Moves this resource to the target resource given by moveTarget.
	// Experimental.
	MoveTo(moveTarget *string, index interface{})
	// Moves this resource to the resource corresponding to "id".
	// Experimental.
	MoveToId(id *string)
	// Overrides the auto-generated logical ID with a specific ID.
	// Experimental.
	OverrideLogicalId(newLogicalId *string)
	PutAzureMonitorWorkspaceIntegrations(value interface{})
	PutIdentity(value *DashboardGrafanaIdentity)
	PutSmtp(value *DashboardGrafanaSmtp)
	PutTimeouts(value *DashboardGrafanaTimeouts)
	ResetApiKeyEnabled()
	ResetAutoGeneratedDomainNameLabelScope()
	ResetAzureMonitorWorkspaceIntegrations()
	ResetDeterministicOutboundIpEnabled()
	ResetId()
	ResetIdentity()
	// Resets a previously passed logical Id to use the auto-generated logical id again.
	// Experimental.
	ResetOverrideLogicalId()
	ResetPublicNetworkAccessEnabled()
	ResetSku()
	ResetSmtp()
	ResetTags()
	ResetTimeouts()
	ResetZoneRedundancyEnabled()
	SynthesizeAttributes() *map[string]interface{}
	SynthesizeHclAttributes() *map[string]interface{}
	// Experimental.
	ToHclTerraform() interface{}
	// Experimental.
	ToMetadata() interface{}
	// Returns a string representation of this construct.
	ToString() *string
	// Adds this resource to the terraform JSON output.
	// Experimental.
	ToTerraform() interface{}
}

// The jsii proxy struct for DashboardGrafana
type jsiiProxy_DashboardGrafana struct {
	internal.Type__cdktfTerraformResource
}

func (j *jsiiProxy_DashboardGrafana) ApiKeyEnabled() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"apiKeyEnabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) ApiKeyEnabledInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"apiKeyEnabledInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) AutoGeneratedDomainNameLabelScope() *string {
	var returns *string
	_jsii_.Get(
		j,
		"autoGeneratedDomainNameLabelScope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) AutoGeneratedDomainNameLabelScopeInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"autoGeneratedDomainNameLabelScopeInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) AzureMonitorWorkspaceIntegrations() DashboardGrafanaAzureMonitorWorkspaceIntegrationsList {
	var returns DashboardGrafanaAzureMonitorWorkspaceIntegrationsList
	_jsii_.Get(
		j,
		"azureMonitorWorkspaceIntegrations",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) AzureMonitorWorkspaceIntegrationsInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"azureMonitorWorkspaceIntegrationsInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) CdktfStack() cdktf.TerraformStack {
	var returns cdktf.TerraformStack
	_jsii_.Get(
		j,
		"cdktfStack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Connection() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"connection",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) ConstructNodeMetadata() *map[string]interface{} {
	var returns *map[string]interface{}
	_jsii_.Get(
		j,
		"constructNodeMetadata",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Count() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"count",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) DependsOn() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"dependsOn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) DeterministicOutboundIpEnabled() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"deterministicOutboundIpEnabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) DeterministicOutboundIpEnabledInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"deterministicOutboundIpEnabledInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Endpoint() *string {
	var returns *string
	_jsii_.Get(
		j,
		"endpoint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) ForEach() cdktf.ITerraformIterator {
	var returns cdktf.ITerraformIterator
	_jsii_.Get(
		j,
		"forEach",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Fqn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"fqn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) FriendlyUniqueId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"friendlyUniqueId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) GrafanaMajorVersion() *string {
	var returns *string
	_jsii_.Get(
		j,
		"grafanaMajorVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) GrafanaMajorVersionInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"grafanaMajorVersionInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) GrafanaVersion() *string {
	var returns *string
	_jsii_.Get(
		j,
		"grafanaVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Identity() DashboardGrafanaIdentityOutputReference {
	var returns DashboardGrafanaIdentityOutputReference
	_jsii_.Get(
		j,
		"identity",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) IdentityInput() *DashboardGrafanaIdentity {
	var returns *DashboardGrafanaIdentity
	_jsii_.Get(
		j,
		"identityInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) IdInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"idInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Lifecycle() *cdktf.TerraformResourceLifecycle {
	var returns *cdktf.TerraformResourceLifecycle
	_jsii_.Get(
		j,
		"lifecycle",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Location() *string {
	var returns *string
	_jsii_.Get(
		j,
		"location",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) LocationInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"locationInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) NameInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"nameInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) OutboundIp() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"outboundIp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Provider() cdktf.TerraformProvider {
	var returns cdktf.TerraformProvider
	_jsii_.Get(
		j,
		"provider",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Provisioners() *[]interface{} {
	var returns *[]interface{}
	_jsii_.Get(
		j,
		"provisioners",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) PublicNetworkAccessEnabled() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"publicNetworkAccessEnabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) PublicNetworkAccessEnabledInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"publicNetworkAccessEnabledInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) RawOverrides() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"rawOverrides",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) ResourceGroupName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"resourceGroupName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) ResourceGroupNameInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"resourceGroupNameInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Sku() *string {
	var returns *string
	_jsii_.Get(
		j,
		"sku",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) SkuInput() *string {
	var returns *string
	_jsii_.Get(
		j,
		"skuInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Smtp() DashboardGrafanaSmtpOutputReference {
	var returns DashboardGrafanaSmtpOutputReference
	_jsii_.Get(
		j,
		"smtp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) SmtpInput() *DashboardGrafanaSmtp {
	var returns *DashboardGrafanaSmtp
	_jsii_.Get(
		j,
		"smtpInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Tags() *map[string]*string {
	var returns *map[string]*string
	_jsii_.Get(
		j,
		"tags",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) TagsInput() *map[string]*string {
	var returns *map[string]*string
	_jsii_.Get(
		j,
		"tagsInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) TerraformGeneratorMetadata() *cdktf.TerraformProviderGeneratorMetadata {
	var returns *cdktf.TerraformProviderGeneratorMetadata
	_jsii_.Get(
		j,
		"terraformGeneratorMetadata",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) TerraformMetaArguments() *map[string]interface{} {
	var returns *map[string]interface{}
	_jsii_.Get(
		j,
		"terraformMetaArguments",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) TerraformResourceType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"terraformResourceType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) Timeouts() DashboardGrafanaTimeoutsOutputReference {
	var returns DashboardGrafanaTimeoutsOutputReference
	_jsii_.Get(
		j,
		"timeouts",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) TimeoutsInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"timeoutsInput",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) ZoneRedundancyEnabled() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"zoneRedundancyEnabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_DashboardGrafana) ZoneRedundancyEnabledInput() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"zoneRedundancyEnabledInput",
		&returns,
	)
	return returns
}


// Create a new {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.28.0/docs/resources/dashboard_grafana azurerm_dashboard_grafana} Resource.
func NewDashboardGrafana(scope constructs.Construct, id *string, config *DashboardGrafanaConfig) DashboardGrafana {
	_init_.Initialize()

	if err := validateNewDashboardGrafanaParameters(scope, id, config); err != nil {
		panic(err)
	}
	j := jsiiProxy_DashboardGrafana{}

	_jsii_.Create(
		"@cdktf/provider-azurerm.dashboardGrafana.DashboardGrafana",
		[]interface{}{scope, id, config},
		&j,
	)

	return &j
}

// Create a new {@link https://registry.terraform.io/providers/hashicorp/azurerm/4.28.0/docs/resources/dashboard_grafana azurerm_dashboard_grafana} Resource.
func NewDashboardGrafana_Override(d DashboardGrafana, scope constructs.Construct, id *string, config *DashboardGrafanaConfig) {
	_init_.Initialize()

	_jsii_.Create(
		"@cdktf/provider-azurerm.dashboardGrafana.DashboardGrafana",
		[]interface{}{scope, id, config},
		d,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetApiKeyEnabled(val interface{}) {
	if err := j.validateSetApiKeyEnabledParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"apiKeyEnabled",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetAutoGeneratedDomainNameLabelScope(val *string) {
	if err := j.validateSetAutoGeneratedDomainNameLabelScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"autoGeneratedDomainNameLabelScope",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetConnection(val interface{}) {
	if err := j.validateSetConnectionParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"connection",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetCount(val interface{}) {
	if err := j.validateSetCountParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"count",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetDependsOn(val *[]*string) {
	_jsii_.Set(
		j,
		"dependsOn",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetDeterministicOutboundIpEnabled(val interface{}) {
	if err := j.validateSetDeterministicOutboundIpEnabledParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"deterministicOutboundIpEnabled",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetForEach(val cdktf.ITerraformIterator) {
	_jsii_.Set(
		j,
		"forEach",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetGrafanaMajorVersion(val *string) {
	if err := j.validateSetGrafanaMajorVersionParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"grafanaMajorVersion",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetLifecycle(val *cdktf.TerraformResourceLifecycle) {
	if err := j.validateSetLifecycleParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"lifecycle",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetLocation(val *string) {
	if err := j.validateSetLocationParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"location",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetName(val *string) {
	if err := j.validateSetNameParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"name",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetProvider(val cdktf.TerraformProvider) {
	_jsii_.Set(
		j,
		"provider",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetProvisioners(val *[]interface{}) {
	if err := j.validateSetProvisionersParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"provisioners",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetPublicNetworkAccessEnabled(val interface{}) {
	if err := j.validateSetPublicNetworkAccessEnabledParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"publicNetworkAccessEnabled",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetResourceGroupName(val *string) {
	if err := j.validateSetResourceGroupNameParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"resourceGroupName",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetSku(val *string) {
	if err := j.validateSetSkuParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"sku",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetTags(val *map[string]*string) {
	if err := j.validateSetTagsParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"tags",
		val,
	)
}

func (j *jsiiProxy_DashboardGrafana)SetZoneRedundancyEnabled(val interface{}) {
	if err := j.validateSetZoneRedundancyEnabledParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"zoneRedundancyEnabled",
		val,
	)
}

// Generates CDKTF code for importing a DashboardGrafana resource upon running "cdktf plan <stack-name>".
func DashboardGrafana_GenerateConfigForImport(scope constructs.Construct, importToId *string, importFromId *string, provider cdktf.TerraformProvider) cdktf.ImportableResource {
	_init_.Initialize()

	if err := validateDashboardGrafana_GenerateConfigForImportParameters(scope, importToId, importFromId); err != nil {
		panic(err)
	}
	var returns cdktf.ImportableResource

	_jsii_.StaticInvoke(
		"@cdktf/provider-azurerm.dashboardGrafana.DashboardGrafana",
		"generateConfigForImport",
		[]interface{}{scope, importToId, importFromId, provider},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
func DashboardGrafana_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateDashboardGrafana_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdktf/provider-azurerm.dashboardGrafana.DashboardGrafana",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Experimental.
func DashboardGrafana_IsTerraformElement(x interface{}) *bool {
	_init_.Initialize()

	if err := validateDashboardGrafana_IsTerraformElementParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdktf/provider-azurerm.dashboardGrafana.DashboardGrafana",
		"isTerraformElement",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Experimental.
func DashboardGrafana_IsTerraformResource(x interface{}) *bool {
	_init_.Initialize()

	if err := validateDashboardGrafana_IsTerraformResourceParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cdktf/provider-azurerm.dashboardGrafana.DashboardGrafana",
		"isTerraformResource",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func DashboardGrafana_TfResourceType() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"@cdktf/provider-azurerm.dashboardGrafana.DashboardGrafana",
		"tfResourceType",
		&returns,
	)
	return returns
}

func (d *jsiiProxy_DashboardGrafana) AddMoveTarget(moveTarget *string) {
	if err := d.validateAddMoveTargetParameters(moveTarget); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"addMoveTarget",
		[]interface{}{moveTarget},
	)
}

func (d *jsiiProxy_DashboardGrafana) AddOverride(path *string, value interface{}) {
	if err := d.validateAddOverrideParameters(path, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"addOverride",
		[]interface{}{path, value},
	)
}

func (d *jsiiProxy_DashboardGrafana) GetAnyMapAttribute(terraformAttribute *string) *map[string]interface{} {
	if err := d.validateGetAnyMapAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *map[string]interface{}

	_jsii_.Invoke(
		d,
		"getAnyMapAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) GetBooleanAttribute(terraformAttribute *string) cdktf.IResolvable {
	if err := d.validateGetBooleanAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns cdktf.IResolvable

	_jsii_.Invoke(
		d,
		"getBooleanAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) GetBooleanMapAttribute(terraformAttribute *string) *map[string]*bool {
	if err := d.validateGetBooleanMapAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *map[string]*bool

	_jsii_.Invoke(
		d,
		"getBooleanMapAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) GetListAttribute(terraformAttribute *string) *[]*string {
	if err := d.validateGetListAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *[]*string

	_jsii_.Invoke(
		d,
		"getListAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) GetNumberAttribute(terraformAttribute *string) *float64 {
	if err := d.validateGetNumberAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *float64

	_jsii_.Invoke(
		d,
		"getNumberAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) GetNumberListAttribute(terraformAttribute *string) *[]*float64 {
	if err := d.validateGetNumberListAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *[]*float64

	_jsii_.Invoke(
		d,
		"getNumberListAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) GetNumberMapAttribute(terraformAttribute *string) *map[string]*float64 {
	if err := d.validateGetNumberMapAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *map[string]*float64

	_jsii_.Invoke(
		d,
		"getNumberMapAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) GetStringAttribute(terraformAttribute *string) *string {
	if err := d.validateGetStringAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		d,
		"getStringAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) GetStringMapAttribute(terraformAttribute *string) *map[string]*string {
	if err := d.validateGetStringMapAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns *map[string]*string

	_jsii_.Invoke(
		d,
		"getStringMapAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) HasResourceMove() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		d,
		"hasResourceMove",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) ImportFrom(id *string, provider cdktf.TerraformProvider) {
	if err := d.validateImportFromParameters(id); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"importFrom",
		[]interface{}{id, provider},
	)
}

func (d *jsiiProxy_DashboardGrafana) InterpolationForAttribute(terraformAttribute *string) cdktf.IResolvable {
	if err := d.validateInterpolationForAttributeParameters(terraformAttribute); err != nil {
		panic(err)
	}
	var returns cdktf.IResolvable

	_jsii_.Invoke(
		d,
		"interpolationForAttribute",
		[]interface{}{terraformAttribute},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) MoveFromId(id *string) {
	if err := d.validateMoveFromIdParameters(id); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"moveFromId",
		[]interface{}{id},
	)
}

func (d *jsiiProxy_DashboardGrafana) MoveTo(moveTarget *string, index interface{}) {
	if err := d.validateMoveToParameters(moveTarget, index); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"moveTo",
		[]interface{}{moveTarget, index},
	)
}

func (d *jsiiProxy_DashboardGrafana) MoveToId(id *string) {
	if err := d.validateMoveToIdParameters(id); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"moveToId",
		[]interface{}{id},
	)
}

func (d *jsiiProxy_DashboardGrafana) OverrideLogicalId(newLogicalId *string) {
	if err := d.validateOverrideLogicalIdParameters(newLogicalId); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"overrideLogicalId",
		[]interface{}{newLogicalId},
	)
}

func (d *jsiiProxy_DashboardGrafana) PutAzureMonitorWorkspaceIntegrations(value interface{}) {
	if err := d.validatePutAzureMonitorWorkspaceIntegrationsParameters(value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"putAzureMonitorWorkspaceIntegrations",
		[]interface{}{value},
	)
}

func (d *jsiiProxy_DashboardGrafana) PutIdentity(value *DashboardGrafanaIdentity) {
	if err := d.validatePutIdentityParameters(value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"putIdentity",
		[]interface{}{value},
	)
}

func (d *jsiiProxy_DashboardGrafana) PutSmtp(value *DashboardGrafanaSmtp) {
	if err := d.validatePutSmtpParameters(value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"putSmtp",
		[]interface{}{value},
	)
}

func (d *jsiiProxy_DashboardGrafana) PutTimeouts(value *DashboardGrafanaTimeouts) {
	if err := d.validatePutTimeoutsParameters(value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"putTimeouts",
		[]interface{}{value},
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetApiKeyEnabled() {
	_jsii_.InvokeVoid(
		d,
		"resetApiKeyEnabled",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetAutoGeneratedDomainNameLabelScope() {
	_jsii_.InvokeVoid(
		d,
		"resetAutoGeneratedDomainNameLabelScope",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetAzureMonitorWorkspaceIntegrations() {
	_jsii_.InvokeVoid(
		d,
		"resetAzureMonitorWorkspaceIntegrations",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetDeterministicOutboundIpEnabled() {
	_jsii_.InvokeVoid(
		d,
		"resetDeterministicOutboundIpEnabled",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetId() {
	_jsii_.InvokeVoid(
		d,
		"resetId",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetIdentity() {
	_jsii_.InvokeVoid(
		d,
		"resetIdentity",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetOverrideLogicalId() {
	_jsii_.InvokeVoid(
		d,
		"resetOverrideLogicalId",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetPublicNetworkAccessEnabled() {
	_jsii_.InvokeVoid(
		d,
		"resetPublicNetworkAccessEnabled",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetSku() {
	_jsii_.InvokeVoid(
		d,
		"resetSku",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetSmtp() {
	_jsii_.InvokeVoid(
		d,
		"resetSmtp",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetTags() {
	_jsii_.InvokeVoid(
		d,
		"resetTags",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetTimeouts() {
	_jsii_.InvokeVoid(
		d,
		"resetTimeouts",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) ResetZoneRedundancyEnabled() {
	_jsii_.InvokeVoid(
		d,
		"resetZoneRedundancyEnabled",
		nil, // no parameters
	)
}

func (d *jsiiProxy_DashboardGrafana) SynthesizeAttributes() *map[string]interface{} {
	var returns *map[string]interface{}

	_jsii_.Invoke(
		d,
		"synthesizeAttributes",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) SynthesizeHclAttributes() *map[string]interface{} {
	var returns *map[string]interface{}

	_jsii_.Invoke(
		d,
		"synthesizeHclAttributes",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) ToHclTerraform() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		d,
		"toHclTerraform",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) ToMetadata() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		d,
		"toMetadata",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		d,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_DashboardGrafana) ToTerraform() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		d,
		"toTerraform",
		nil, // no parameters
		&returns,
	)

	return returns
}

