//go:build no_runtime_type_checking

package dashboardgrafana

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DashboardGrafana) validateAddOverrideParameters(path *string, value interface{}) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validateOverrideLogicalIdParameters(newLogicalId *string) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validatePutIdentityParameters(value *DashboardGrafanaIdentity) error {
	return nil
}

func (d *jsiiProxy_DashboardGrafana) validatePutTimeoutsParameters(value *DashboardGrafanaTimeouts) error {
	return nil
}

func validateDashboardGrafana_IsConstructParameters(x interface{}) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetApiKeyEnabledParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetAutoGeneratedDomainNameLabelScopeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetConnectionParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetDeterministicOutboundIpEnabledParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetIdParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetLifecycleParameters(val *cdktf.TerraformResourceLifecycle) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetLocationParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetNameParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetProvisionersParameters(val *[]interface{}) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetPublicNetworkAccessEnabledParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetResourceGroupNameParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetSkuParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetTagsParameters(val *map[string]*string) error {
	return nil
}

func (j *jsiiProxy_DashboardGrafana) validateSetZoneRedundancyEnabledParameters(val interface{}) error {
	return nil
}

func validateNewDashboardGrafanaParameters(scope constructs.Construct, id *string, config *DashboardGrafanaConfig) error {
	return nil
}

